theme: minima
title: Continuous Learning
author: Johan Sundström
email: serializr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal notebook for continuous learning.
  
# social links
twitter_username: serializr # DO NOT include the @ character, or else the build will fail!
github_username:  serializr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
